### ISSUE TITLE
Documentation gaps for `apply_to_config` usage

### ISSUE THREAD

**Issue by maverick1872** [MLFlexer/modal.wezterm#28]
Hey! Wanted to provide some feedback on my time trying to trial this implementation alongside Wezterm and some of the hurdles I encountered during setup. Took me a bit to sort through them but the following are huddles of note.

1. Implementation of `apply_to_config` relies on a theme that has the Wezterm Retro colors defined. Specifically this [block](https://github.com/MLFlexer/modal.wezterm/blob/b47c910ab5f6203ef60e1ab747ae16a8e0577659/plugin/init.lua#L189-L193) is where the assumption arises. Enabling fallback colors here would be one potential resolution. 
2. Implementation of `apply_to_config` attempts to insert into the `config.keys` table but does not handle the case where that table is not yet defined. Specifically [this block](https://github.com/MLFlexer/modal.wezterm/blob/b47c910ab5f6203ef60e1ab747ae16a8e0577659/plugin/init.lua#L233-L247) is where the assumption arises.

Both of these issues are mostly just a direct byproduct of the fact that I'm relying on the default configuration for Wezterm as I'm currently just trialing. The tab bar colors though would need minor additional considerations as not all themes define tab bar colors.

**Comment by maverick1872** [comment]
Additionally, newcomers would likely appreciate if the README were to defined the mode activation key bindings that `apply_to_config` defines, rather than requiring people to parse the `init.lua`.

**Comment by MLFlexer** [comment]
Thank you for letting me know about these issues in such a detailed manner, I really appreciate it! 😄 

I agree that the readme should include the mode activation key, and maybe also a section of the keybindings for each mode, such that they are easy to read, instead of relying on reading the code for the specific modes.
